name: inception

networks:
  internal:

services:
  nginx:
    networks:
      - internal
    volumes:
      - wordpress_vol:/var/www/wordpress
    build: ./requirements/nginx
    ports:
      - "443:443"
    secrets:
      - ssl_cert
      - ssl_key
    depends_on:
      - wordpress
    restart: on-failure

  database:
    networks:
      - internal
    build:
      context: ./requirements/database
      dockerfile: Dockerfile
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
    volumes:
      - database_vol:/var/lib/mysql
    restart: on-failure
    secrets:
      - db_passwd
      - db_root_passwd

  wordpress:
    networks:
      - internal
    depends_on:
      - database
    build: ./requirements/wordpress
    volumes:
      - wordpress_vol:/var/www/wordpress
    secrets:
      - db_passwd
      - wp_admin_passwd
    environment:
      MYSQL_HOST: $MYSQL_HOST
      MYSQL_PORT: $MYSQL_PORT
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE

      WP_ADMIN_NAME: $WP_ADMIN_NAME
      WP_ADMIN_PASSWORD: $WP_ADMIN_PASSWORD
      WP_ADMIN_MAIL: $WP_ADMIN_MAIL

      WP_USER_NAME: $WP_USER_NAME
      WP_USER_PASSWORD: $WP_USER_PASSWORD
      WP_USER_MAIL: $WP_USER_MAIL
    restart: on-failure

secrets:
  ssl_cert:
    file: $SSLCRTPATH
  ssl_key:
    file: $SSLKEYPATH
  db_passwd:
    file: $MYSQL_PASSWORD_PATH
  db_root_passwd:
    file: $MYSQL_ROOT_PASSWORD_PATH
  wp_admin_passwd:
    file: $WP_ADMIN_PASSWORD_PATH

volumes:
  database_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/bajeanno/data/mariadb'
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/bajeanno/data/wordpress'